# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'credit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_credit(object):
    def setupUi(self, credit):
        credit.setObjectName("credit")
        credit.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(credit)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.credit_name = QtWidgets.QLabel(self.centralwidget)
        self.credit_name.setGeometry(QtCore.QRect(20, 140, 761, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.credit_name.setFont(font)
        self.credit_name.setText("")
        self.credit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.credit_name.setObjectName("credit_name")
        self.goBack = QtWidgets.QPushButton(self.centralwidget)
        self.goBack.setGeometry(QtCore.QRect(370, 360, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goBack.setFont(font)
        self.goBack.setObjectName("goBack")
        credit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(credit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        credit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(credit)
        self.statusbar.setObjectName("statusbar")
        credit.setStatusBar(self.statusbar)

        self.retranslateUi(credit)
        QtCore.QMetaObject.connectSlotsByName(credit)

    def retranslateUi(self, credit):
        _translate = QtCore.QCoreApplication.translate
        credit.setWindowTitle(_translate("credit", "MainWindow"))
        self.label.setText(_translate("credit", "Credits"))
        self.goBack.setText(_translate("credit", "Go Back"))
